/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/notifications'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/notifications'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/notifications'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ApiChatRoute: typeof ApiChatRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ApiChatRoute: ApiChatRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
