/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPublishingRouteImport } from './routes/_authenticated/publishing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedSettingsSocialHealthRouteImport } from './routes/_authenticated/settings.social-health'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPluginsRouteImport } from './routes/_authenticated/settings.plugins'
import { Route as AuthenticatedSettingsDeveloperRouteImport } from './routes/_authenticated/settings.developer'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings.connections'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedPublishingQueueRouteImport } from './routes/_authenticated/publishing.queue'
import { Route as AuthenticatedPublishingMediaRouteImport } from './routes/_authenticated/publishing.media'
import { Route as AuthenticatedPublishingDraftsRouteImport } from './routes/_authenticated/publishing.drafts'
import { Route as AuthenticatedPublishingComposeRouteImport } from './routes/_authenticated/publishing.compose'
import { Route as AuthenticatedPublishingCalendarRouteImport } from './routes/_authenticated/publishing.calendar'
import { Route as AuthenticatedPublishingApprovalsRouteImport } from './routes/_authenticated/publishing.approvals'
import { Route as AuthenticatedAnalyticsWebsiteRouteImport } from './routes/_authenticated/analytics.website'
import { Route as AuthenticatedAnalyticsUnifiedRouteImport } from './routes/_authenticated/analytics.unified'
import { Route as AuthenticatedAnalyticsSeoRouteImport } from './routes/_authenticated/analytics.seo'
import { Route as AuthenticatedAnalyticsRevenueRouteImport } from './routes/_authenticated/analytics.revenue'
import { Route as AuthenticatedAnalyticsReportsRouteImport } from './routes/_authenticated/analytics.reports'
import { Route as AuthenticatedAnalyticsPlatformsRouteImport } from './routes/_authenticated/analytics.platforms'
import { Route as AuthenticatedAnalyticsOverviewRouteImport } from './routes/_authenticated/analytics.overview'
import { Route as AuthenticatedAnalyticsForecastingRouteImport } from './routes/_authenticated/analytics.forecasting'
import { Route as AuthenticatedAnalyticsDeveloperRouteImport } from './routes/_authenticated/analytics.developer'
import { Route as AuthenticatedAnalyticsCustomRouteImport } from './routes/_authenticated/analytics.custom'
import { Route as AuthenticatedAnalyticsContentRouteImport } from './routes/_authenticated/analytics.content'
import { Route as AuthenticatedAnalyticsCompetitorRouteImport } from './routes/_authenticated/analytics.competitor'
import { Route as AuthenticatedAnalyticsChartsRouteImport } from './routes/_authenticated/analytics.charts'
import { Route as AuthenticatedAnalyticsCampaignsRouteImport } from './routes/_authenticated/analytics.campaigns'
import { Route as AuthenticatedAnalyticsAudienceRouteImport } from './routes/_authenticated/analytics.audience'
import { Route as AuthenticatedAnalyticsAlertsRouteImport } from './routes/_authenticated/analytics.alerts'
import { Route as AuthenticatedAnalyticsAiInsightsRouteImport } from './routes/_authenticated/analytics.ai-insights'
import { Route as AuthenticatedAnalyticsAdvertisingRouteImport } from './routes/_authenticated/analytics.advertising'
import { Route as AuthenticatedAnalyticsMetricRouteImport } from './routes/_authenticated/analytics.$metric'
import { Route as ApiPublicHooksGenerateWeeklyReportsRouteImport } from './routes/api/public/hooks/generate-weekly-reports'
import { Route as ApiPublicCronSocialSyncRouteImport } from './routes/api/public/cron/social-sync'
import { Route as ApiPublicCronPublishRouteImport } from './routes/api/public/cron/publish'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishingRoute = AuthenticatedPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedSettingsSocialHealthRoute =
  AuthenticatedSettingsSocialHealthRouteImport.update({
    id: '/settings/social-health',
    path: '/settings/social-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPluginsRoute =
  AuthenticatedSettingsPluginsRouteImport.update({
    id: '/settings/plugins',
    path: '/settings/plugins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDeveloperRoute =
  AuthenticatedSettingsDeveloperRouteImport.update({
    id: '/settings/developer',
    path: '/settings/developer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReportsRoute,
} as any)
const AuthenticatedPublishingQueueRoute =
  AuthenticatedPublishingQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedPublishingMediaRoute =
  AuthenticatedPublishingMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedPublishingDraftsRoute =
  AuthenticatedPublishingDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedPublishingComposeRoute =
  AuthenticatedPublishingComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedPublishingCalendarRoute =
  AuthenticatedPublishingCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedPublishingApprovalsRoute =
  AuthenticatedPublishingApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedPublishingRoute,
  } as any)
const AuthenticatedAnalyticsWebsiteRoute =
  AuthenticatedAnalyticsWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsUnifiedRoute =
  AuthenticatedAnalyticsUnifiedRouteImport.update({
    id: '/unified',
    path: '/unified',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsSeoRoute =
  AuthenticatedAnalyticsSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsRevenueRoute =
  AuthenticatedAnalyticsRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsReportsRoute =
  AuthenticatedAnalyticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsPlatformsRoute =
  AuthenticatedAnalyticsPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsOverviewRoute =
  AuthenticatedAnalyticsOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsForecastingRoute =
  AuthenticatedAnalyticsForecastingRouteImport.update({
    id: '/forecasting',
    path: '/forecasting',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsDeveloperRoute =
  AuthenticatedAnalyticsDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsCustomRoute =
  AuthenticatedAnalyticsCustomRouteImport.update({
    id: '/custom',
    path: '/custom',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsContentRoute =
  AuthenticatedAnalyticsContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsCompetitorRoute =
  AuthenticatedAnalyticsCompetitorRouteImport.update({
    id: '/competitor',
    path: '/competitor',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsChartsRoute =
  AuthenticatedAnalyticsChartsRouteImport.update({
    id: '/charts',
    path: '/charts',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsCampaignsRoute =
  AuthenticatedAnalyticsCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsAudienceRoute =
  AuthenticatedAnalyticsAudienceRouteImport.update({
    id: '/audience',
    path: '/audience',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsAlertsRoute =
  AuthenticatedAnalyticsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsAiInsightsRoute =
  AuthenticatedAnalyticsAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsAdvertisingRoute =
  AuthenticatedAnalyticsAdvertisingRouteImport.update({
    id: '/advertising',
    path: '/advertising',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsMetricRoute =
  AuthenticatedAnalyticsMetricRouteImport.update({
    id: '/$metric',
    path: '/$metric',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const ApiPublicHooksGenerateWeeklyReportsRoute =
  ApiPublicHooksGenerateWeeklyReportsRouteImport.update({
    id: '/api/public/hooks/generate-weekly-reports',
    path: '/api/public/hooks/generate-weekly-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSocialSyncRoute = ApiPublicCronSocialSyncRouteImport.update({
  id: '/api/public/cron/social-sync',
  path: '/api/public/cron/social-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPublishRoute = ApiPublicCronPublishRouteImport.update({
  id: '/api/public/cron/publish',
  path: '/api/public/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/publishing': typeof AuthenticatedPublishingRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/analytics/$metric': typeof AuthenticatedAnalyticsMetricRoute
  '/analytics/advertising': typeof AuthenticatedAnalyticsAdvertisingRoute
  '/analytics/ai-insights': typeof AuthenticatedAnalyticsAiInsightsRoute
  '/analytics/alerts': typeof AuthenticatedAnalyticsAlertsRoute
  '/analytics/audience': typeof AuthenticatedAnalyticsAudienceRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/charts': typeof AuthenticatedAnalyticsChartsRoute
  '/analytics/competitor': typeof AuthenticatedAnalyticsCompetitorRoute
  '/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/analytics/custom': typeof AuthenticatedAnalyticsCustomRoute
  '/analytics/developer': typeof AuthenticatedAnalyticsDeveloperRoute
  '/analytics/forecasting': typeof AuthenticatedAnalyticsForecastingRoute
  '/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/analytics/platforms': typeof AuthenticatedAnalyticsPlatformsRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/revenue': typeof AuthenticatedAnalyticsRevenueRoute
  '/analytics/seo': typeof AuthenticatedAnalyticsSeoRoute
  '/analytics/unified': typeof AuthenticatedAnalyticsUnifiedRoute
  '/analytics/website': typeof AuthenticatedAnalyticsWebsiteRoute
  '/publishing/approvals': typeof AuthenticatedPublishingApprovalsRoute
  '/publishing/calendar': typeof AuthenticatedPublishingCalendarRoute
  '/publishing/compose': typeof AuthenticatedPublishingComposeRoute
  '/publishing/drafts': typeof AuthenticatedPublishingDraftsRoute
  '/publishing/media': typeof AuthenticatedPublishingMediaRoute
  '/publishing/queue': typeof AuthenticatedPublishingQueueRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/social-health': typeof AuthenticatedSettingsSocialHealthRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/social-sync': typeof ApiPublicCronSocialSyncRoute
  '/api/public/hooks/generate-weekly-reports': typeof ApiPublicHooksGenerateWeeklyReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/publishing': typeof AuthenticatedPublishingRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/analytics/$metric': typeof AuthenticatedAnalyticsMetricRoute
  '/analytics/advertising': typeof AuthenticatedAnalyticsAdvertisingRoute
  '/analytics/ai-insights': typeof AuthenticatedAnalyticsAiInsightsRoute
  '/analytics/alerts': typeof AuthenticatedAnalyticsAlertsRoute
  '/analytics/audience': typeof AuthenticatedAnalyticsAudienceRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/charts': typeof AuthenticatedAnalyticsChartsRoute
  '/analytics/competitor': typeof AuthenticatedAnalyticsCompetitorRoute
  '/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/analytics/custom': typeof AuthenticatedAnalyticsCustomRoute
  '/analytics/developer': typeof AuthenticatedAnalyticsDeveloperRoute
  '/analytics/forecasting': typeof AuthenticatedAnalyticsForecastingRoute
  '/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/analytics/platforms': typeof AuthenticatedAnalyticsPlatformsRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/revenue': typeof AuthenticatedAnalyticsRevenueRoute
  '/analytics/seo': typeof AuthenticatedAnalyticsSeoRoute
  '/analytics/unified': typeof AuthenticatedAnalyticsUnifiedRoute
  '/analytics/website': typeof AuthenticatedAnalyticsWebsiteRoute
  '/publishing/approvals': typeof AuthenticatedPublishingApprovalsRoute
  '/publishing/calendar': typeof AuthenticatedPublishingCalendarRoute
  '/publishing/compose': typeof AuthenticatedPublishingComposeRoute
  '/publishing/drafts': typeof AuthenticatedPublishingDraftsRoute
  '/publishing/media': typeof AuthenticatedPublishingMediaRoute
  '/publishing/queue': typeof AuthenticatedPublishingQueueRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/social-health': typeof AuthenticatedSettingsSocialHealthRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/social-sync': typeof ApiPublicCronSocialSyncRoute
  '/api/public/hooks/generate-weekly-reports': typeof ApiPublicHooksGenerateWeeklyReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assistant': typeof AssistantRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design': typeof DesignRoute
  '/notifications': typeof NotificationsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/publishing': typeof AuthenticatedPublishingRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/_authenticated/analytics/$metric': typeof AuthenticatedAnalyticsMetricRoute
  '/_authenticated/analytics/advertising': typeof AuthenticatedAnalyticsAdvertisingRoute
  '/_authenticated/analytics/ai-insights': typeof AuthenticatedAnalyticsAiInsightsRoute
  '/_authenticated/analytics/alerts': typeof AuthenticatedAnalyticsAlertsRoute
  '/_authenticated/analytics/audience': typeof AuthenticatedAnalyticsAudienceRoute
  '/_authenticated/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/_authenticated/analytics/charts': typeof AuthenticatedAnalyticsChartsRoute
  '/_authenticated/analytics/competitor': typeof AuthenticatedAnalyticsCompetitorRoute
  '/_authenticated/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/_authenticated/analytics/custom': typeof AuthenticatedAnalyticsCustomRoute
  '/_authenticated/analytics/developer': typeof AuthenticatedAnalyticsDeveloperRoute
  '/_authenticated/analytics/forecasting': typeof AuthenticatedAnalyticsForecastingRoute
  '/_authenticated/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/_authenticated/analytics/platforms': typeof AuthenticatedAnalyticsPlatformsRoute
  '/_authenticated/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/_authenticated/analytics/revenue': typeof AuthenticatedAnalyticsRevenueRoute
  '/_authenticated/analytics/seo': typeof AuthenticatedAnalyticsSeoRoute
  '/_authenticated/analytics/unified': typeof AuthenticatedAnalyticsUnifiedRoute
  '/_authenticated/analytics/website': typeof AuthenticatedAnalyticsWebsiteRoute
  '/_authenticated/publishing/approvals': typeof AuthenticatedPublishingApprovalsRoute
  '/_authenticated/publishing/calendar': typeof AuthenticatedPublishingCalendarRoute
  '/_authenticated/publishing/compose': typeof AuthenticatedPublishingComposeRoute
  '/_authenticated/publishing/drafts': typeof AuthenticatedPublishingDraftsRoute
  '/_authenticated/publishing/media': typeof AuthenticatedPublishingMediaRoute
  '/_authenticated/publishing/queue': typeof AuthenticatedPublishingQueueRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/_authenticated/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/social-health': typeof AuthenticatedSettingsSocialHealthRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/cron/social-sync': typeof ApiPublicCronSocialSyncRoute
  '/api/public/hooks/generate-weekly-reports': typeof ApiPublicHooksGenerateWeeklyReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/design'
    | '/notifications'
    | '/analytics'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/onboarding'
    | '/publishing'
    | '/reports'
    | '/tasks'
    | '/team'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/settings/notifications'
    | '/analytics/$metric'
    | '/analytics/advertising'
    | '/analytics/ai-insights'
    | '/analytics/alerts'
    | '/analytics/audience'
    | '/analytics/campaigns'
    | '/analytics/charts'
    | '/analytics/competitor'
    | '/analytics/content'
    | '/analytics/custom'
    | '/analytics/developer'
    | '/analytics/forecasting'
    | '/analytics/overview'
    | '/analytics/platforms'
    | '/analytics/reports'
    | '/analytics/revenue'
    | '/analytics/seo'
    | '/analytics/unified'
    | '/analytics/website'
    | '/publishing/approvals'
    | '/publishing/calendar'
    | '/publishing/compose'
    | '/publishing/drafts'
    | '/publishing/media'
    | '/publishing/queue'
    | '/reports/$id'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/social-health'
    | '/analytics/'
    | '/api/public/cron/publish'
    | '/api/public/cron/social-sync'
    | '/api/public/hooks/generate-weekly-reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/design'
    | '/notifications'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/onboarding'
    | '/publishing'
    | '/reports'
    | '/tasks'
    | '/team'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/settings/notifications'
    | '/analytics/$metric'
    | '/analytics/advertising'
    | '/analytics/ai-insights'
    | '/analytics/alerts'
    | '/analytics/audience'
    | '/analytics/campaigns'
    | '/analytics/charts'
    | '/analytics/competitor'
    | '/analytics/content'
    | '/analytics/custom'
    | '/analytics/developer'
    | '/analytics/forecasting'
    | '/analytics/overview'
    | '/analytics/platforms'
    | '/analytics/reports'
    | '/analytics/revenue'
    | '/analytics/seo'
    | '/analytics/unified'
    | '/analytics/website'
    | '/publishing/approvals'
    | '/publishing/calendar'
    | '/publishing/compose'
    | '/publishing/drafts'
    | '/publishing/media'
    | '/publishing/queue'
    | '/reports/$id'
    | '/settings/connections'
    | '/settings/developer'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/social-health'
    | '/analytics'
    | '/api/public/cron/publish'
    | '/api/public/cron/social-sync'
    | '/api/public/hooks/generate-weekly-reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assistant'
    | '/auth'
    | '/design'
    | '/notifications'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/insights'
    | '/_authenticated/onboarding'
    | '/_authenticated/publishing'
    | '/_authenticated/reports'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/settings/notifications'
    | '/_authenticated/analytics/$metric'
    | '/_authenticated/analytics/advertising'
    | '/_authenticated/analytics/ai-insights'
    | '/_authenticated/analytics/alerts'
    | '/_authenticated/analytics/audience'
    | '/_authenticated/analytics/campaigns'
    | '/_authenticated/analytics/charts'
    | '/_authenticated/analytics/competitor'
    | '/_authenticated/analytics/content'
    | '/_authenticated/analytics/custom'
    | '/_authenticated/analytics/developer'
    | '/_authenticated/analytics/forecasting'
    | '/_authenticated/analytics/overview'
    | '/_authenticated/analytics/platforms'
    | '/_authenticated/analytics/reports'
    | '/_authenticated/analytics/revenue'
    | '/_authenticated/analytics/seo'
    | '/_authenticated/analytics/unified'
    | '/_authenticated/analytics/website'
    | '/_authenticated/publishing/approvals'
    | '/_authenticated/publishing/calendar'
    | '/_authenticated/publishing/compose'
    | '/_authenticated/publishing/drafts'
    | '/_authenticated/publishing/media'
    | '/_authenticated/publishing/queue'
    | '/_authenticated/reports/$id'
    | '/_authenticated/settings/connections'
    | '/_authenticated/settings/developer'
    | '/_authenticated/settings/plugins'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/social-health'
    | '/_authenticated/analytics/'
    | '/api/public/cron/publish'
    | '/api/public/cron/social-sync'
    | '/api/public/hooks/generate-weekly-reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssistantRoute: typeof AssistantRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignRoute: typeof DesignRoute
  NotificationsRoute: typeof NotificationsRoute
  ApiChatRoute: typeof ApiChatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  ApiPublicCronPublishRoute: typeof ApiPublicCronPublishRoute
  ApiPublicCronSocialSyncRoute: typeof ApiPublicCronSocialSyncRoute
  ApiPublicHooksGenerateWeeklyReportsRoute: typeof ApiPublicHooksGenerateWeeklyReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishing': {
      id: '/_authenticated/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AuthenticatedPublishingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/settings/social-health': {
      id: '/_authenticated/settings/social-health'
      path: '/settings/social-health'
      fullPath: '/settings/social-health'
      preLoaderRoute: typeof AuthenticatedSettingsSocialHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/plugins': {
      id: '/_authenticated/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/developer': {
      id: '/_authenticated/settings/developer'
      path: '/settings/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AuthenticatedSettingsDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/publishing/queue': {
      id: '/_authenticated/publishing/queue'
      path: '/queue'
      fullPath: '/publishing/queue'
      preLoaderRoute: typeof AuthenticatedPublishingQueueRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/publishing/media': {
      id: '/_authenticated/publishing/media'
      path: '/media'
      fullPath: '/publishing/media'
      preLoaderRoute: typeof AuthenticatedPublishingMediaRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/publishing/drafts': {
      id: '/_authenticated/publishing/drafts'
      path: '/drafts'
      fullPath: '/publishing/drafts'
      preLoaderRoute: typeof AuthenticatedPublishingDraftsRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/publishing/compose': {
      id: '/_authenticated/publishing/compose'
      path: '/compose'
      fullPath: '/publishing/compose'
      preLoaderRoute: typeof AuthenticatedPublishingComposeRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/publishing/calendar': {
      id: '/_authenticated/publishing/calendar'
      path: '/calendar'
      fullPath: '/publishing/calendar'
      preLoaderRoute: typeof AuthenticatedPublishingCalendarRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/publishing/approvals': {
      id: '/_authenticated/publishing/approvals'
      path: '/approvals'
      fullPath: '/publishing/approvals'
      preLoaderRoute: typeof AuthenticatedPublishingApprovalsRouteImport
      parentRoute: typeof AuthenticatedPublishingRoute
    }
    '/_authenticated/analytics/website': {
      id: '/_authenticated/analytics/website'
      path: '/website'
      fullPath: '/analytics/website'
      preLoaderRoute: typeof AuthenticatedAnalyticsWebsiteRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/unified': {
      id: '/_authenticated/analytics/unified'
      path: '/unified'
      fullPath: '/analytics/unified'
      preLoaderRoute: typeof AuthenticatedAnalyticsUnifiedRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/seo': {
      id: '/_authenticated/analytics/seo'
      path: '/seo'
      fullPath: '/analytics/seo'
      preLoaderRoute: typeof AuthenticatedAnalyticsSeoRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/revenue': {
      id: '/_authenticated/analytics/revenue'
      path: '/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AuthenticatedAnalyticsRevenueRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/reports': {
      id: '/_authenticated/analytics/reports'
      path: '/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/platforms': {
      id: '/_authenticated/analytics/platforms'
      path: '/platforms'
      fullPath: '/analytics/platforms'
      preLoaderRoute: typeof AuthenticatedAnalyticsPlatformsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/overview': {
      id: '/_authenticated/analytics/overview'
      path: '/overview'
      fullPath: '/analytics/overview'
      preLoaderRoute: typeof AuthenticatedAnalyticsOverviewRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/forecasting': {
      id: '/_authenticated/analytics/forecasting'
      path: '/forecasting'
      fullPath: '/analytics/forecasting'
      preLoaderRoute: typeof AuthenticatedAnalyticsForecastingRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/developer': {
      id: '/_authenticated/analytics/developer'
      path: '/developer'
      fullPath: '/analytics/developer'
      preLoaderRoute: typeof AuthenticatedAnalyticsDeveloperRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/custom': {
      id: '/_authenticated/analytics/custom'
      path: '/custom'
      fullPath: '/analytics/custom'
      preLoaderRoute: typeof AuthenticatedAnalyticsCustomRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/content': {
      id: '/_authenticated/analytics/content'
      path: '/content'
      fullPath: '/analytics/content'
      preLoaderRoute: typeof AuthenticatedAnalyticsContentRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/competitor': {
      id: '/_authenticated/analytics/competitor'
      path: '/competitor'
      fullPath: '/analytics/competitor'
      preLoaderRoute: typeof AuthenticatedAnalyticsCompetitorRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/charts': {
      id: '/_authenticated/analytics/charts'
      path: '/charts'
      fullPath: '/analytics/charts'
      preLoaderRoute: typeof AuthenticatedAnalyticsChartsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/campaigns': {
      id: '/_authenticated/analytics/campaigns'
      path: '/campaigns'
      fullPath: '/analytics/campaigns'
      preLoaderRoute: typeof AuthenticatedAnalyticsCampaignsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/audience': {
      id: '/_authenticated/analytics/audience'
      path: '/audience'
      fullPath: '/analytics/audience'
      preLoaderRoute: typeof AuthenticatedAnalyticsAudienceRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/alerts': {
      id: '/_authenticated/analytics/alerts'
      path: '/alerts'
      fullPath: '/analytics/alerts'
      preLoaderRoute: typeof AuthenticatedAnalyticsAlertsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/ai-insights': {
      id: '/_authenticated/analytics/ai-insights'
      path: '/ai-insights'
      fullPath: '/analytics/ai-insights'
      preLoaderRoute: typeof AuthenticatedAnalyticsAiInsightsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/advertising': {
      id: '/_authenticated/analytics/advertising'
      path: '/advertising'
      fullPath: '/analytics/advertising'
      preLoaderRoute: typeof AuthenticatedAnalyticsAdvertisingRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/$metric': {
      id: '/_authenticated/analytics/$metric'
      path: '/$metric'
      fullPath: '/analytics/$metric'
      preLoaderRoute: typeof AuthenticatedAnalyticsMetricRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/api/public/hooks/generate-weekly-reports': {
      id: '/api/public/hooks/generate-weekly-reports'
      path: '/api/public/hooks/generate-weekly-reports'
      fullPath: '/api/public/hooks/generate-weekly-reports'
      preLoaderRoute: typeof ApiPublicHooksGenerateWeeklyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/social-sync': {
      id: '/api/public/cron/social-sync'
      path: '/api/public/cron/social-sync'
      fullPath: '/api/public/cron/social-sync'
      preLoaderRoute: typeof ApiPublicCronSocialSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/publish': {
      id: '/api/public/cron/publish'
      path: '/api/public/cron/publish'
      fullPath: '/api/public/cron/publish'
      preLoaderRoute: typeof ApiPublicCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsMetricRoute: typeof AuthenticatedAnalyticsMetricRoute
  AuthenticatedAnalyticsAdvertisingRoute: typeof AuthenticatedAnalyticsAdvertisingRoute
  AuthenticatedAnalyticsAiInsightsRoute: typeof AuthenticatedAnalyticsAiInsightsRoute
  AuthenticatedAnalyticsAlertsRoute: typeof AuthenticatedAnalyticsAlertsRoute
  AuthenticatedAnalyticsAudienceRoute: typeof AuthenticatedAnalyticsAudienceRoute
  AuthenticatedAnalyticsCampaignsRoute: typeof AuthenticatedAnalyticsCampaignsRoute
  AuthenticatedAnalyticsChartsRoute: typeof AuthenticatedAnalyticsChartsRoute
  AuthenticatedAnalyticsCompetitorRoute: typeof AuthenticatedAnalyticsCompetitorRoute
  AuthenticatedAnalyticsContentRoute: typeof AuthenticatedAnalyticsContentRoute
  AuthenticatedAnalyticsCustomRoute: typeof AuthenticatedAnalyticsCustomRoute
  AuthenticatedAnalyticsDeveloperRoute: typeof AuthenticatedAnalyticsDeveloperRoute
  AuthenticatedAnalyticsForecastingRoute: typeof AuthenticatedAnalyticsForecastingRoute
  AuthenticatedAnalyticsOverviewRoute: typeof AuthenticatedAnalyticsOverviewRoute
  AuthenticatedAnalyticsPlatformsRoute: typeof AuthenticatedAnalyticsPlatformsRoute
  AuthenticatedAnalyticsReportsRoute: typeof AuthenticatedAnalyticsReportsRoute
  AuthenticatedAnalyticsRevenueRoute: typeof AuthenticatedAnalyticsRevenueRoute
  AuthenticatedAnalyticsSeoRoute: typeof AuthenticatedAnalyticsSeoRoute
  AuthenticatedAnalyticsUnifiedRoute: typeof AuthenticatedAnalyticsUnifiedRoute
  AuthenticatedAnalyticsWebsiteRoute: typeof AuthenticatedAnalyticsWebsiteRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsMetricRoute: AuthenticatedAnalyticsMetricRoute,
    AuthenticatedAnalyticsAdvertisingRoute:
      AuthenticatedAnalyticsAdvertisingRoute,
    AuthenticatedAnalyticsAiInsightsRoute:
      AuthenticatedAnalyticsAiInsightsRoute,
    AuthenticatedAnalyticsAlertsRoute: AuthenticatedAnalyticsAlertsRoute,
    AuthenticatedAnalyticsAudienceRoute: AuthenticatedAnalyticsAudienceRoute,
    AuthenticatedAnalyticsCampaignsRoute: AuthenticatedAnalyticsCampaignsRoute,
    AuthenticatedAnalyticsChartsRoute: AuthenticatedAnalyticsChartsRoute,
    AuthenticatedAnalyticsCompetitorRoute:
      AuthenticatedAnalyticsCompetitorRoute,
    AuthenticatedAnalyticsContentRoute: AuthenticatedAnalyticsContentRoute,
    AuthenticatedAnalyticsCustomRoute: AuthenticatedAnalyticsCustomRoute,
    AuthenticatedAnalyticsDeveloperRoute: AuthenticatedAnalyticsDeveloperRoute,
    AuthenticatedAnalyticsForecastingRoute:
      AuthenticatedAnalyticsForecastingRoute,
    AuthenticatedAnalyticsOverviewRoute: AuthenticatedAnalyticsOverviewRoute,
    AuthenticatedAnalyticsPlatformsRoute: AuthenticatedAnalyticsPlatformsRoute,
    AuthenticatedAnalyticsReportsRoute: AuthenticatedAnalyticsReportsRoute,
    AuthenticatedAnalyticsRevenueRoute: AuthenticatedAnalyticsRevenueRoute,
    AuthenticatedAnalyticsSeoRoute: AuthenticatedAnalyticsSeoRoute,
    AuthenticatedAnalyticsUnifiedRoute: AuthenticatedAnalyticsUnifiedRoute,
    AuthenticatedAnalyticsWebsiteRoute: AuthenticatedAnalyticsWebsiteRoute,
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedPublishingRouteChildren {
  AuthenticatedPublishingApprovalsRoute: typeof AuthenticatedPublishingApprovalsRoute
  AuthenticatedPublishingCalendarRoute: typeof AuthenticatedPublishingCalendarRoute
  AuthenticatedPublishingComposeRoute: typeof AuthenticatedPublishingComposeRoute
  AuthenticatedPublishingDraftsRoute: typeof AuthenticatedPublishingDraftsRoute
  AuthenticatedPublishingMediaRoute: typeof AuthenticatedPublishingMediaRoute
  AuthenticatedPublishingQueueRoute: typeof AuthenticatedPublishingQueueRoute
}

const AuthenticatedPublishingRouteChildren: AuthenticatedPublishingRouteChildren =
  {
    AuthenticatedPublishingApprovalsRoute:
      AuthenticatedPublishingApprovalsRoute,
    AuthenticatedPublishingCalendarRoute: AuthenticatedPublishingCalendarRoute,
    AuthenticatedPublishingComposeRoute: AuthenticatedPublishingComposeRoute,
    AuthenticatedPublishingDraftsRoute: AuthenticatedPublishingDraftsRoute,
    AuthenticatedPublishingMediaRoute: AuthenticatedPublishingMediaRoute,
    AuthenticatedPublishingQueueRoute: AuthenticatedPublishingQueueRoute,
  }

const AuthenticatedPublishingRouteWithChildren =
  AuthenticatedPublishingRoute._addFileChildren(
    AuthenticatedPublishingRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPublishingRoute: typeof AuthenticatedPublishingRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsDeveloperRoute: typeof AuthenticatedSettingsDeveloperRoute
  AuthenticatedSettingsPluginsRoute: typeof AuthenticatedSettingsPluginsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSocialHealthRoute: typeof AuthenticatedSettingsSocialHealthRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPublishingRoute: AuthenticatedPublishingRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsDeveloperRoute: AuthenticatedSettingsDeveloperRoute,
  AuthenticatedSettingsPluginsRoute: AuthenticatedSettingsPluginsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSocialHealthRoute:
    AuthenticatedSettingsSocialHealthRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssistantRoute: AssistantRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignRoute: DesignRoute,
  NotificationsRoute: NotificationsRoute,
  ApiChatRoute: ApiChatRoute,
  InviteTokenRoute: InviteTokenRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  ApiPublicCronPublishRoute: ApiPublicCronPublishRoute,
  ApiPublicCronSocialSyncRoute: ApiPublicCronSocialSyncRoute,
  ApiPublicHooksGenerateWeeklyReportsRoute:
    ApiPublicHooksGenerateWeeklyReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
